### ISSUE TITLE
Retain speed and altitude while switching mode

### ISSUE THREAD

**Issue by Brusura** [Boris-Barboris/AtmosphereAutopilot#7]
Ie from fly-by-wire to cruise mode , speed and altitude should be retained from previous mode when switching

**Comment by Boris-Barboris** [comment]
Neo-GUI?

**Comment by Brusura** [comment]
Yes Neo-GUI

**Comment by Boris-Barboris** [comment]
Not sure what you ment, but try dropbox build [https://dl.dropboxusercontent.com/u/23572905/KSP_Mods/AtmosphereAutopilot/AtmosphereAutopilot_1.5.7.zip](url)
Should make altitude control switch off by default when you activate cruise control.

**Comment by Brusura** [comment]
I'll try the new build, I'll try to explain , if you set cruise at 10k altitude and then switch to fly-by-wire and say you go at 1k altitude if you swith again to cruise mode the plane will start to climb because cruise is set to 10k , what I am asking is to keep current altitude ( and speed ) because when I switch to cruise mode I want set maybe a new altitude and not the old one avoiding unwanted change in altitude while switching mode

http://forum.kerbalspaceprogram.com/index.php?/topic/124417-113-atmosphereautopilot-156/&do=findComment&comment=2669358

PS: build link is broken

**Comment by Boris-Barboris** [comment]
Oh, I see now. Unbroken link is in the OP on forum, strangely it's the same i provided here (idk, github markdown bug maybe).

I'll deal with it after 5-6 days, need to give a lot of attention to RL atm, but I got your point, sounds legit for neo-gui. Let the dropbox build be a quick bandaid, it should prevent sudden spasm, caused by altitude control, at least.

**Comment by Boris-Barboris** [comment]
Still can be on when activating CF first time (idk why), but works as intended after that.
